### ISSUE TITLE
Tải phim đuôi m3u8

### ISSUE THREAD

**Issue by vumail159951** [hoangvu12/netime-server-new#1]
Ông ơi, ông biết cách nào tải film vuighe.net không,
T dùng phần mềm mà ko tải được hic
Good repo

**Comment by hoangvu12** [comment]
Xài thử extension này đi 
https://chrome.google.com/webstore/detail/m3u8-downloaderdownload-m/gddbgllpilhpnjpkdbopahnpealaklle
